default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: 5
  username: <%= ENV["db_user"]%>
  password: <%= ENV["db_password"]%>
  host: <%= ENV["db_host"]%>

development:
  <<: *default
  database: <%= ENV["database"]%>

test:
  <<: *default
  database: <%= ENV["database"]%>

production:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: 5
  username: <%= ENV["db_user"]%>
  password: <%= ENV["db_password"]%>
  host: <%= ENV["db_host"]%>
  database: <%= ENV["database"]%>